apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: self-security
  labels:
    app: suricata
  
spec:
  selector:
    matchLabels:
      app: suricata
  template:
    metadata:
      labels:
        app: suricata
      name: suricata
    spec:
      hostIPC: true
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: init-obtain-interface
          image: busybox
          command:
            - /bin/sh
            - "-c"
            - |
              # Obtain the default network interface and save it to a file.
              INTERFACE=$(ip -o -4 route show to default | awk '{print $5}')
              echo "$INTERFACE" > /mnt/shared/interface.txt
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared
      containers:
        - name: log-cleaner
          image: busybox
          command:
            - /bin/sh
            - "-c"
            - |
              while true; do
                echo "Cleaning suricata logs in $(hostname)..."
                echo "" > /var/log/suricata/fast.log
                sleep 604800  # wait one week(604800 seconds)
              done
          volumeMounts:
            - name: suricata-logs
              mountPath: /var/log/suricata
          securityContext:
            privileged: true
        - name: suricata
          image: registry.gitlab.aeros-project.eu/aeros-public/common-deployments/self-security/self-security 
          securityContext:
            privileged: true
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared
            - mountPath: /host/dev
              name: dev
            - mountPath: /var/run/docker.sock
              name: docker-socket-mount
            - name: suricata-log-pv
              mountPath: "/var/log/suricata"
            - mountPath: /etc/suricata/suricata.yaml
              name: suricata-config
              subPath: suricata.yaml
            - mountPath: /var/lib/suricata/rules/suricata.rules
              name: suricata-rules
              subPath: suricata.rules          
          command:
            - /bin/sh
            - "-c"
            - |
              # Read the interface from the file generated by the init container
              INTERFACE=$(cat /mnt/shared/interface.txt)
              echo "Using interface $INTERFACE for Suricata"
              # Start Suricata in listening mode on the detected interface
              suricata -i "$INTERFACE" -c /etc/suricata/suricata.yaml --af-packet
        - name: python-etl
          image: registry.gitlab.aeros-project.eu/aeros-public/common-deployments/self-security/etl
          env:
            - name: ENDPOINT_URL
              value: "http://ENDPOINT_URL"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: Password_Admin
              value: "Admin Password"
            - name: Userpassword
              value: "User PassWord@"
          volumeMounts:
            - name: suricata-log-pv
              mountPath: "/var/log/suricata"

        - name: suricata-api
          securityContext: {}
          image: registry.gitlab.aeros-project.eu/aeros-public/common-deployments/self-security/api
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: suricata-log-pv
              mountPath: "/var/log/suricata"

      imagePullSecrets:
        - name: aeros-common-deployments
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
        - name: suricata-config
          configMap:
            name: suricata-config
        - name: suricata-rules
          configMap:
            name: suricata-rules
        - name: suricata-log-pv
          hostPath:
            path: /var/log/suricata
        - name: shared-data
          emptyDir: {}
        - name: suricata-logs
          hostPath:
            path: /var/log/suricata
            type: Directory
#        - name: suricata-log-pv
#          persistentVolumeClaim:
#            claimName: suricata-log-pv-claim